name: tci-represent
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - debugpy=1.8.14=py310hf71b8c6_0
  - ipykernel=6.29.5=pyh3099207_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.5.0=h7b32b05_1
  - pip=25.1=pyhc872135_2
  - python=3.10.16=he870216_1
  - python_abi=3.10=2_cp310
  - pyzmq=25.1.2=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - accelerate==1.7.0
      - addict==2.4.0
      - altair==5.5.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - attrs==25.3.0
      - bleach==6.2.0
      - blinker==1.9.0
      - blis==0.7.11
      - braceexpand==0.1.7
      - cachetools==5.5.2
      - catalogue==2.0.10
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - comm==0.2.2
      - confection==0.1.5
      - configargparse==1.7
      - contexttimer==0.3.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - cymem==2.0.11
      - dash==3.0.4
      - decorator==4.4.2
      - decord==0.6.0
      - diffusers==0.16.0
      - distlib==0.3.9
      - easydict==1.9
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fairscale==0.4.4
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - flask==3.0.3
      - fonttools==4.58.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.71.0
      - h5py==3.13.0
      - huggingface-hub==0.22.2
      - identify==2.6.10
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - iopath==0.1.10
      - ipython==8.36.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.15
      - kaggle==1.7.4.5
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - lmdb==1.6.2
      - marisa-trie==1.2.1
      - markdown==3.8
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - moviepy==1.0.3
      - mpmath==1.3.0
      - murmurhash==1.0.12
      - narwhals==1.40.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - peft==0.10.0
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - plotly==6.1.1
      - portalocker==3.1.1
      - pre-commit==4.2.0
      - preshed==3.0.9
      - proglog==0.1.12
      - prompt-toolkit==3.0.51
      - protobuf==6.31.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pycparser==2.22
      - pydantic==1.10.22
      - pydeck==0.9.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-magic==0.4.27
      - python-slugify==8.0.4
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyyaml-env-tag==0.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - retrying==1.3.4
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - salesforce-lavis==1.0.1
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - six==1.17.0
      - smart-open==6.4.0
      - smmap==5.0.2
      - soundfile==0.13.1
      - spacy==3.6.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack-data==0.6.3
      - streamlit==1.45.1
      - sympy==1.13.3
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - text-unidecode==1.3
      - thinc==8.1.12
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==0.4.12
      - tokenizers==0.13.3
      - toml==0.10.2
      - torch==2.7.0+cu118
      - torchaudio==2.7.0+cu118
      - torchvision==0.22.0+cu118
      - tornado==6.5
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.33.2
      - triton==3.3.0
      - typer==0.9.4
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - virtualenv==20.31.2
      - wasabi==1.1.3
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - webdataset==0.2.111
      - webencodings==0.5.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - zipp==3.21.0
prefix: /home/h_zhou/workspace3/miniconda3/envs/tcdui310
